# Continuos Delivery/Deployment to Docker Hub

on:
  push:
    tags:
        - "v*.*.*"
        
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - id: get_version
        uses: battila7/get-version-action@v2

      - run: echo "CONTAINER_VERSION=${{ steps.get_version.outputs.version-without-v }}" >> $GITHUB_ENV 

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Build
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build zsh
        id: build_zsh
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          build-args: |
            VERSION=${{ steps.get_version.outputs.version-without-v }} 
          push: true
          tags: |
            seebaktec/zsh:latest
            seebaktec/zsh:${{ env.CONTAINER_VERSION }}
            
      - name: Image digest
        run: echo ${{ steps.build_zsh.outputs.digest }}
